### PR TITLE
Added path arguments to specify modules and destination folders

### PR DESCRIPTION
**Pull request by alebiavati**
This pull request adds arguments to the `pac` and `pac install` commads to specify the path to the `.modules`, `node_modules` and `bower_components` folders. I am using this in a pretty strict build system that prevents anything to be written in the project folder.

This is not really necessary for bower since you could specify the destination folder in the project's `.bowerrc`, but I added the option for the bower strategy as well for consistency.

### CODE REVIEW

**Comment by mikefrey** [comment]
@alebiavati I like the change! Would you mind adding some unit tests for this functionality?

**Comment by alebiavati** [comment]
Cool, I'll do that soon.

**Comment by philBrown** [comment]
Just a quick note about the `dest` option... shouldn't it use the configured paths in `.npmrc` / `.bowerrc` (if they exist) before reverting to the default `node_modules` / `bower_components`?

**Comment by alebiavati** [comment]
Yes, the module already takes into account directory in `.bowerrc`, but I don't think you can specify a custom folder for node modules via `.npmrc`.

**Comment by philBrown** [comment]
Thanks, you're correct of course. The documentation doesn't mention the `.bowerrc` file but I see it's in the bower strategy file.

Can't wait to see this released, great work @alebiavati!

**Pull request closed without merging**
